development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  channel_prefix: hello_rails_production
  host: <%= ENV["REDIS_HOST"] %>
  port: <%= ENV["REDIS_PORT"] %>
  password: <%= ENV["REDIS_PASSWORD"] %>
  ssl: true
